language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
notifications:
  email: false
addons:
  apt:
    packages:
    - golang
before_install:
 - export GOPATH=~/go
 - go get github.com/uiri/toml-test
 - pip install flake8
install:
 - python setup.py install
 - chmod +x ./tests/*.sh
script:
 - ~/go/bin/toml-test ./tests/decoding_test.sh
 - flake8
